name: 'Configure AWS Credentials'
description: 'Configure AWS credentials and profile'
inputs:
  aws-region:
    description: 'AWS Region'
    required: true
  aws-account-id:
    description: 'AWS Account ID'
    required: true
  oidc-role-name:
    description: 'OIDC Role Name'
    required: true
  aws-account-profile:
    description: 'AWS Account Profile Name'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/${{ inputs.oidc-role-name }}
        role-session-name: ${{ inputs.aws-account-profile }}
        mask-aws-account-id: 'no'

    - name: Setup AWS Profile
      shell: bash
      run: |
        aws configure set region ${{ inputs.aws-region }} --profile ${{ inputs.aws-account-profile }}
        aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }} --profile ${{ inputs.aws-account-profile }}
        aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }} --profile ${{ inputs.aws-account-profile }}
        aws configure set aws_session_token ${{ env.AWS_SESSION_TOKEN }} --profile ${{ inputs.aws-account-profile }}

    - name: Reset AWS Environment Variables to use profile
      shell: bash
      run: |
        echo "AWS_ACCESS_KEY_ID=" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=" >> $GITHUB_ENV
        echo "AWS_SESSION_TOKEN=" >> $GITHUB_ENV
