name: Deploy to Prod Environment on Pull Request

on:
  pull_request:
    branches: [prod]

# common env variables
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
  ZEPTO_MAIL_API_KEY: ${{ secrets.ZEPTO_MAIL_API_KEY }}
  PADDLE_API_KEY: ${{ secrets.PADDLE_API_KEY }}
  PADDLE_WEBHOOK_SECRET_KEY: ${{ secrets.PADDLE_WEBHOOK_SECRET_KEY }}
  VAPID_PRIVATE_KEY: ${{ secrets.VAPID_PRIVATE_KEY }}
  VAPID_PUBLIC_KEY: ${{ secrets.VAPID_PUBLIC_KEY }}
  OIDC_ROLE_NAME: ${{ secrets.AWS_GITHUB_OIDC_ROLE }}

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-go-node

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          install-mode: 'goinstall'

      - name: Install testifylint
        run: |
          go install github.com/Antonboom/testifylint@latest

      - name: Run linting
        run: make lint-all

      - name: Run unit tests
        run: make test-unit

      - name: Run integration tests
        run: make test-integration

  deploy-test:
    needs: lint-and-test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: true
    env:
      DEPLOY_STAGE: 'test'
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID_TEST }}
      AWS_ACCOUNT_PROFILE: ${{ secrets.AWS_ACCOUNT_PROFILE_TEST }}

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-go-node

      - name: Install CDK
        run: |
          pnpm install -g aws-cdk

      # custom AWS configure action
      - uses: ./.github/actions/aws-configure
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-account-id: ${{ env.AWS_ACCOUNT_ID }}
          oidc-role-name: ${{ env.OIDC_ROLE_NAME }}
          aws-account-profile: ${{ env.AWS_ACCOUNT_PROFILE }}

      - name: Run infrastructure tests
        run: make test-infra

      - name: Deploy to test environment
        run: make cdk-deploy-main-no-approval

      - name: Run E2E tests
        run: make test-e2e

      - name: Cleanup test environment
        if: always()
        run: make test-cleanup

  deploy-prod:
    needs: deploy-test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: true
    env:
      #   TODO: Add prod aws secrets (account id)
      DEPLOY_STAGE: 'prod'
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID_PROD }}
      API_DOMAIN_NAME: ${{ secrets.API_DOMAIN_NAME_PROD }}
      AWS_ACCOUNT_PROFILE: ${{ secrets.AWS_ACCOUNT_PROFILE_PROD }}

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-go-node

      - name: Install CDK
        run: |
          pnpm install -g aws-cdk

      # Use the custom AWS configure action
      - uses: ./.github/actions/aws-configure
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-account-id: ${{ env.AWS_ACCOUNT_ID }}
          oidc-role-name: ${{ env.OIDC_ROLE_NAME }}
          aws-account-profile: ${{ env.AWS_ACCOUNT_PROFILE }}

      - name: Deploy to production environment
        run: make cdk-deploy-main-no-approval
